
package com.joe.ws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IOrderService", targetNamespace = "http://ws.joe.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IOrderService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.joe.ws.client.Order
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrder", targetNamespace = "http://ws.joe.com", className = "com.joe.ws.client.GetOrder")
    @ResponseWrapper(localName = "getOrderResponse", targetNamespace = "http://ws.joe.com", className = "com.joe.ws.client.GetOrderResponse")
    public Order getOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.joe.ws.client.Order>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrders", targetNamespace = "http://ws.joe.com", className = "com.joe.ws.client.GetOrders")
    @ResponseWrapper(localName = "getOrdersResponse", targetNamespace = "http://ws.joe.com", className = "com.joe.ws.client.GetOrdersResponse")
    public List<Order> getOrders();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserName", targetNamespace = "http://ws.joe.com", className = "com.joe.ws.client.GetUserName")
    @ResponseWrapper(localName = "getUserNameResponse", targetNamespace = "http://ws.joe.com", className = "com.joe.ws.client.GetUserNameResponse")
    public String getUserName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
