
package com.joe.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrderServiceBean", targetNamespace = "http://ws.joe.com", wsdlLocation = "http://127.0.0.1:8080/WebService/OrderServiceBean?wsdl")
public class OrderServiceBean
    extends Service
{

    private final static URL ORDERSERVICEBEAN_WSDL_LOCATION;
    private final static WebServiceException ORDERSERVICEBEAN_EXCEPTION;
    private final static QName ORDERSERVICEBEAN_QNAME = new QName("http://ws.joe.com", "OrderServiceBean");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/WebService/OrderServiceBean?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERSERVICEBEAN_WSDL_LOCATION = url;
        ORDERSERVICEBEAN_EXCEPTION = e;
    }

    public OrderServiceBean() {
        super(__getWsdlLocation(), ORDERSERVICEBEAN_QNAME);
    }

    public OrderServiceBean(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERSERVICEBEAN_QNAME);
//    	super(__getWsdlLocation(), ORDERSERVICEBEAN_QNAME, features);
    }

    public OrderServiceBean(URL wsdlLocation) {
        super(wsdlLocation, ORDERSERVICEBEAN_QNAME);
    }

    public OrderServiceBean(URL wsdlLocation, WebServiceFeature... features) {
        //super(wsdlLocation, ORDERSERVICEBEAN_QNAME, features);
    	super(__getWsdlLocation(), ORDERSERVICEBEAN_QNAME);
    }

    public OrderServiceBean(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderServiceBean(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        //super(wsdlLocation, serviceName, features);
    	super(__getWsdlLocation(), ORDERSERVICEBEAN_QNAME);
    }

    /**
     * 
     * @return
     *     returns IOrderService
     */
    @WebEndpoint(name = "IOrderServicePort")
    public IOrderService getIOrderServicePort() {
        return super.getPort(new QName("http://ws.joe.com", "IOrderServicePort"), IOrderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IOrderService
     */
    @WebEndpoint(name = "IOrderServicePort")
    public IOrderService getIOrderServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.joe.com", "IOrderServicePort"), IOrderService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERSERVICEBEAN_EXCEPTION!= null) {
            throw ORDERSERVICEBEAN_EXCEPTION;
        }
        return ORDERSERVICEBEAN_WSDL_LOCATION;
    }

}
